apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: scv-backend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: scvfealias=ghcr.io/mhughdo/scv-backend
    argocd-image-updater.argoproj.io/scvfealias.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: default
  source:
    repoURL: https://github.com/mhughdo/scv-backend
    targetRevision: HEAD
    path: k8s/base
  destination:
    server: https://kubernetes.default.svc
    namespace: scv
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
