// Code generated by SQLBoiler 4.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// This test suite runs each operation test in parallel.
// Example, if your database has 3 tables, the suite will run:
// table1, table2 and table3 Delete in parallel
// table1, table2 and table3 Insert in parallel, and so forth.
// It does NOT run each operation group in parallel.
// Separating the tests thusly grants avoidance of Postgres deadlocks.
func TestParent(t *testing.T) {
	t.Run("Files", testFiles)
	t.Run("GooseDBVersions", testGooseDBVersions)
	t.Run("Languages", testLanguages)
}

func TestDelete(t *testing.T) {
	t.Run("Files", testFilesDelete)
	t.Run("GooseDBVersions", testGooseDBVersionsDelete)
	t.Run("Languages", testLanguagesDelete)
}

func TestQueryDeleteAll(t *testing.T) {
	t.Run("Files", testFilesQueryDeleteAll)
	t.Run("GooseDBVersions", testGooseDBVersionsQueryDeleteAll)
	t.Run("Languages", testLanguagesQueryDeleteAll)
}

func TestSliceDeleteAll(t *testing.T) {
	t.Run("Files", testFilesSliceDeleteAll)
	t.Run("GooseDBVersions", testGooseDBVersionsSliceDeleteAll)
	t.Run("Languages", testLanguagesSliceDeleteAll)
}

func TestExists(t *testing.T) {
	t.Run("Files", testFilesExists)
	t.Run("GooseDBVersions", testGooseDBVersionsExists)
	t.Run("Languages", testLanguagesExists)
}

func TestFind(t *testing.T) {
	t.Run("Files", testFilesFind)
	t.Run("GooseDBVersions", testGooseDBVersionsFind)
	t.Run("Languages", testLanguagesFind)
}

func TestBind(t *testing.T) {
	t.Run("Files", testFilesBind)
	t.Run("GooseDBVersions", testGooseDBVersionsBind)
	t.Run("Languages", testLanguagesBind)
}

func TestOne(t *testing.T) {
	t.Run("Files", testFilesOne)
	t.Run("GooseDBVersions", testGooseDBVersionsOne)
	t.Run("Languages", testLanguagesOne)
}

func TestAll(t *testing.T) {
	t.Run("Files", testFilesAll)
	t.Run("GooseDBVersions", testGooseDBVersionsAll)
	t.Run("Languages", testLanguagesAll)
}

func TestCount(t *testing.T) {
	t.Run("Files", testFilesCount)
	t.Run("GooseDBVersions", testGooseDBVersionsCount)
	t.Run("Languages", testLanguagesCount)
}

func TestHooks(t *testing.T) {
	t.Run("Files", testFilesHooks)
	t.Run("GooseDBVersions", testGooseDBVersionsHooks)
	t.Run("Languages", testLanguagesHooks)
}

func TestInsert(t *testing.T) {
	t.Run("Files", testFilesInsert)
	t.Run("Files", testFilesInsertWhitelist)
	t.Run("GooseDBVersions", testGooseDBVersionsInsert)
	t.Run("GooseDBVersions", testGooseDBVersionsInsertWhitelist)
	t.Run("Languages", testLanguagesInsert)
	t.Run("Languages", testLanguagesInsertWhitelist)
}

// TestToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestToOne(t *testing.T) {
	t.Run("FileToLanguageUsingLanguage", testFileToOneLanguageUsingLanguage)
}

// TestOneToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOne(t *testing.T) {
	t.Run("LanguageToFileUsingFile", testLanguageOneToOneFileUsingFile)
}

// TestToMany tests cannot be run in parallel
// or deadlocks can occur.
func TestToMany(t *testing.T) {}

// TestToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneSet(t *testing.T) {
	t.Run("FileToLanguageUsingFile", testFileToOneSetOpLanguageUsingLanguage)
}

// TestToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneRemove(t *testing.T) {}

// TestOneToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneSet(t *testing.T) {
	t.Run("LanguageToFileUsingFile", testLanguageOneToOneSetOpFileUsingFile)
}

// TestOneToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneRemove(t *testing.T) {}

// TestToManyAdd tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyAdd(t *testing.T) {}

// TestToManySet tests cannot be run in parallel
// or deadlocks can occur.
func TestToManySet(t *testing.T) {}

// TestToManyRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyRemove(t *testing.T) {}

func TestReload(t *testing.T) {
	t.Run("Files", testFilesReload)
	t.Run("GooseDBVersions", testGooseDBVersionsReload)
	t.Run("Languages", testLanguagesReload)
}

func TestReloadAll(t *testing.T) {
	t.Run("Files", testFilesReloadAll)
	t.Run("GooseDBVersions", testGooseDBVersionsReloadAll)
	t.Run("Languages", testLanguagesReloadAll)
}

func TestSelect(t *testing.T) {
	t.Run("Files", testFilesSelect)
	t.Run("GooseDBVersions", testGooseDBVersionsSelect)
	t.Run("Languages", testLanguagesSelect)
}

func TestUpdate(t *testing.T) {
	t.Run("Files", testFilesUpdate)
	t.Run("GooseDBVersions", testGooseDBVersionsUpdate)
	t.Run("Languages", testLanguagesUpdate)
}

func TestSliceUpdateAll(t *testing.T) {
	t.Run("Files", testFilesSliceUpdateAll)
	t.Run("GooseDBVersions", testGooseDBVersionsSliceUpdateAll)
	t.Run("Languages", testLanguagesSliceUpdateAll)
}
