// Code generated by SQLBoiler 4.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Files          string
	GooseDBVersion string
	Languages      string
}{
	Files:          "files",
	GooseDBVersion: "goose_db_version",
	Languages:      "languages",
}
